### ISSUE TITLE
Not working from today

### ISSUE THREAD

**Issue by amrashraf1992** [Yash-K-B/YoutubeExtractor#11]
Error in extraction :
                 org.mozilla.javascript.EvaluatorException: missing ] after element list (script#7236)
                 	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:79)
                 	at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:66)
                 	at org.mozilla.javascript.Parser.addError(Parser.java:257)
                 	at org.mozilla.javascript.Parser.reportError(Parser.java:336)
                 	at org.mozilla.javascript.Parser.reportError(Parser.java:327)
                 	at org.mozilla.javascript.Parser.reportError(Parser.java:320)
                 	at org.mozilla.javascript.Parser.arrayLiteral(Parser.java:3222)
                 	at org.mozilla.javascript.Parser.primaryExpr(Parser.java:3045)
                 	at org.mozilla.javascript.Parser.memberExpr(Parser.java:2671)
                 	at org.mozilla.javascript.Parser.unaryExpr(Parser.java:2574)
                 	at org.mozilla.javascript.Parser.expExpr(Parser.java:2494)
                 	at org.mozilla.javascript.Parser.mulExpr(Parser.java:2477)
                 	at org.mozilla.javascript.Parser.addExpr(Parser.java:2463)
                 	at org.mozilla.javascript.Parser.shiftExpr(Parser.java:2446)
                 	at org.mozilla.javascript.Parser.relExpr(Parser.java:2424)
                 	at org.mozilla.javascript.Parser.eqExpr(Parser.java:2400)
                 	at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:2391)
                 	at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:2382)
                 	at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:2373)
                 	at org.mozilla.javascript.Parser.andExpr(Parser.java:2364)
                 	at org.mozilla.javascript.Parser.orExpr(Parser.java:2355)
                 	at org.mozilla.javascript.Parser.condExpr(Parser.java:2322)
                 	at org.mozilla.javascript.Parser.assignExpr(Parser.java:2280)
                 	at org.mozilla.javascript.Parser.variables(Parser.java:2128)
                 	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1197)
                 	at org.mozilla.javascript.Parser.statement(Parser.java:1104)
                 	at org.mozilla.javascript.Parser.parse(Parser.java:632)
                 	at org.mozilla.javascript.Parser.parse(Parser.java:562)
                 	at org.mozilla.javascript.Context.parse(Context.java:2470)
                 	at org.mozilla.javascript.Context.compileImpl(Context.java:2401)
                 	at org.mozilla.javascript.Context.compileString(Context.java:1369)
                 	at org.mozilla.javascript.Context.compileString(Context.java:1357)
                 	at org.mozilla.javascript.Context.evaluateString(Context.java:1135)
                 	at com.yash.youtube_extractor.Extractor.extract(Extractor.java:167)

**Comment by amrashraf1992** [comment]
Please update ??

**Comment by Dolanpls** [comment]
Maybe you can provide more information like the used video ID, some code, etc.
That would help to find the issue

**Comment by Yash-K-B** [comment]
I think this issue arise in some video ids, please provide the same.

**Comment by amrashraf1992** [comment]
you are right only some videos
